### ISSUE TITLE
Spelling and meaning checks

### ISSUE THREAD

**Issue by LambdaHidden** [NovaDiablox/stealth2.1turkishlocalization#1]
I'm checking your translation before officially adding it to the mod (please keep in mind I don't understand Turkish at all and am relying on translation software), and I'm seeing some things Google and DeepL are both reporting as mistakes:

- `stealth_keepcorpses.name` is mistranslated as "override the bodies" or "invalidate corpses", while `stealth_keepcorpses.help` does correctly describe what the command does.
- "uyutulduklarında" is a misspelling of "unutulduklarında".
- `stealth_lightfactor.help` translates to "Determines how much the burning player's visibility is affected." I tried to rephrase the original text and DeepL gave me "Oyuncu üzerinde parlayan ışığın görünürlüğünü nasıl etkileyeceğini ayarlar." would that work?
- `stealth_backuptime.name` translates to "Support request duration", when it should mean "Support request delay". Both suggested me "Destek talebi gecikmesi".
- `stealth_cheat_no_alert.name` Translates to "Cheat: no trigger pull". Both translators suggested "Hile: uyarı yok".
- The last verse of the poem in `stealth_cheat_no_alert.help` says "you can see me", when the point of the joke is that NPCs _cannot_ see you.
- Google detected a misspelling in `stealth_cloak_allowed.help`.
- In `stealth_musicpath.help`, "something" should be translated to Turkish.
- `stealth_toggle_cloak_bind.name` suggests that the button is what gets enabled/disabled, rather than the button toggling the invisibility. 

Also, I'll add `stealth.cilentsettings.name=Client Settings` and `stealth.serversettings.name=Server Settings` at the top of the file in the next update.

**Comment by NovaDiablox** [comment]
1. is correct. The Garry's Mod Turkish Translation also uses that translation so I went with that. It seems like the meaning was lost. Will fix it soon.

2. is wrong there is no misspelling. "unutulduklarında" means "when they are forgotten" DeepL might try to fix non-existent errors.

3. is correct, that would work greatly. DeepL gave you a good one.

4. can be used interchangeably. In source language it still means the duration [delay] it takes them to come to help [support]. I can change it to DeepL's suggestion in this case.

5. sounds like a word for word translation. In my translation it means "cheat: no alert" "tetiğe geçme yok" still means "being alerted" or "being aware of your surrondings when something is wrong" in others words "being alerted"

6. I totally messed it up. I found the song but didn't understand it a bit. It was 1 or 2 am for me when I was translating it. My bad for not leaving a note says "Not ready yet, don't merge". Will fix it soon.

7. At "gizleme". Will fix it soon.
8. Yeah it should be.
9. Will fix it soon

And will add next updates text. I hope the clarification helps in some mistakes and DeepL's behaviour.

**Comment by NovaDiablox** [comment]
The command you are referring to might be ai_serverragdolls. Would you like me to change that as well?

**Comment by NovaDiablox** [comment]
It's done.
